### ISSUE TITLE
Keeping current - libbitcoin-explorer

### ISSUE THREAD

**Issue by skaht** [WyseNynja/homebrew-bitcoin#55]
FYSA -  See the September 5th posting at https://github.com/libbitcoin/libbitcoin-explorer/pull/269#issuecomment-137988187. Contains concise information for building libbitcoin-explorer that has BIP 32, 38, 39, and 44 key generation capabilities. Good info to help seed this repo.

**Comment by fanquake** [comment]
I've just removed all the old/broken libbitcoin related formula. There was no point continuing to serve them as they were.

Pull requests always welcome, I've had a bit of a look into writing updated formula, and given how the libbitcoin install process currently works, it might not even fit as a formula any more.

**Comment by skaht** [comment]
The libbitcoin guys move at blazing speeds. Will share my cshell scripts with you after the big BIP 38 upgrade finishes its Beta.

Got one cshell script for each of the dozen or so packages required to build bx and bs.
